### ISSUE TITLE
interesting codepens

### ISSUE THREAD

**Issue by Rplus** [Rplus/f2e-note#15]
collections of fun codepen

**Comment by Rplus** [comment]
CSS only clicking game
http://codepen.io/web-tiki/pen/NPeKbE/?editors=010

有趣的應用了 `counter-increment` 來計數
因為 `counter-increment` 只計一次的緣故，能巧妙地一併算出剩餘數量

``` css
input{
  counter-increment: input;
}

input:checked {
  counter-increment: checked;
}
```

**Comment by Rplus** [comment]
CSS Walking Animation
http://codepen.io/web-tiki/pen/NqjKze/?editors=010
模擬走路動態的 CSS animation 作品

Running CSS animation
http://codepen.io/web-tiki/details/gpWLbW
跑步版本

Running CSS animation
http://codepen.io/yukulele/details/aOwGmY/
有人 fork 去調整成有自然傾角的狀態

**Comment by Rplus** [comment]
Text with 3D shadow
http://codepen.io/web-tiki/details/azeKNy

以 `rotateX(90deg)` 模擬陰影傾角旋轉的變化

**Comment by Rplus** [comment]
CSS responsive grid of hexagons
http://codepen.io/web-tiki/pen/HhCyd/?editors=010

實心 hexagons 作法：
雙層 `overfow: hidden`
- 外層 `rotate(-60deg) skewY(30deg)`
- 內層 `skewY(-30deg) rotate(60deg)`

可處理 mouseenter 邊界問題
(用 border 組出來的會有)

**Comment by Rplus** [comment]
CSS transparent strike through
http://codepen.io/web-tiki/details/YXwyRa

先以 pseudo element 夾出一條縫模擬 strike through 效果
再用 svg mask fill 實作靈活的 strike through

**Comment by Rplus** [comment]
CSS Hexagon - the basics (SO)
http://codepen.io/thebabydino/details/sJdgu

神奇操作
用 pseudo-element 的話，可以單元素達成六邊形
主要是內部的圖片裁切完美
還能轉~ 讚讚讚

我把算式用 Stylus 公式化了
http://codepen.io/Rplus/pen/BNdgoJ.stylus
demo: http://codepen.io/Rplus/details/BNdgoJ

**Comment by Rplus** [comment]
http://codepen.io/thebabydino/details/MwEbwE/

gradient 裡用 `calc(50% - 1px)` `calc(50% + 1px)`
來制作出 2px 的直線 XDDD

**Comment by Rplus** [comment]
CSS Only Poseable Mannequin
http://codepen.io/neoberg/details/doVQqv/

肢體動作 by CSS control

**Comment by Rplus** [comment]
Logo animation
http://codepen.io/makegraff/details/gpoaJG/

主要是利用 timing-function 做超過臨界點的擺盪
`cubic-bezier(0.66, -0.7, 0.27, 1.6)`

![image](https://cloud.githubusercontent.com/assets/1808835/8401672/878b4f52-1e64-11e5-9f78-05ccda8fe3af.png)

**Comment by Rplus** [comment]
Download Cards
http://codepen.io/EvanWieland/details/zGPXpK

這個是典型的 flip type 的旋轉效果
搭配與上則一樣的  over-transtion 來達到更加擬真的 3D 翻轉效果

切換翻轉的按鈕位置設計可以再調整一下
位置不一，有反下意識操作的困擾

**Comment by Rplus** [comment]
Adaptive tabs
http://codepen.io/Lewitje/details/doJRBX

這一例中的 color picker 利用 border-radius 很巧妙地模擬了立體陰影
相當值得學習

另外對於 `:hover` , `.active` 的狀態也處理得相當合理且易於辨別
浮出凸顯有幾個樣式: 不破壞左右間距的 `scale()`、帶有背景陰影、自體陰影範圍加大

![image](https://cloud.githubusercontent.com/assets/1808835/8401889/10b737f2-1e68-11e5-98b1-9e0ecdb924f4.png)

**Comment by Rplus** [comment]
textarea auto-expainding height
http://codepen.io/vsync/details/frudD
https://gist.github.com/CodeMyUI/51c9d6e83db8653b3e5c

自動長高的 textarea

很聰明的作法呀~
雖然目前 textarea 很常被用 contenteditable 取代
不過原生的輸入框還是有它的特性 ( 純文字 、表單 ~ )

它偵測 input event 來調整 row 數值 (抓 `textarea.scrollHeight` )
不過它的 lineHeight 為何要寫死為 17px 呀？
( 但 window.getComputedStyle 出來的都是 normal 是怎麼算呀 = =

**Comment by Rplus** [comment]
it's those damn xenomorphs again
http://codepen.io/lesbaa/details/MYLoRp/

moveit 的動畫效果很棒
模擬傳統電視電漿啟動的扭曲感

``` css
@keyframes moveit {
  0%      { transform: translateX(0); }
  28.99%  { transform: translateY(0); }
  29%     { transform: translateY(5px) skewX(20deg); }
  30%     { transform: translate(0); }
  88.999% { transform: translate(0); }
  89%     { transform: skewX(-15deg); }
  89.001% { transform: skew(0); }
  90%     { transform: translate(0); }
  90.001% { transform: translate(23px, 17px); }
  98.999% { transform: translate(22px, 20px); }
  99%     { transform: translate(0); }
  100%    { transform: translate(0) skew(0); }
}
```

**Comment by Rplus** [comment]
HR with centered text
http://codepen.io/scottzirkel/details/yNxNME/

`<hr>` 是個頗趣味的 tag
設定成 block level 後可以塞進 pseudo-element

**Comment by Rplus** [comment]
Gooey Beach Ball Loader
http://codepen.io/Henri-K/pen/doqWdo

用 `filter: blur()` 創建的 svg goo effect

**Comment by Rplus** [comment]
A Pen by Marcello Insolera
http://codepen.io/frontend_marcello/pen/aOaLrb?editors=010

clip 的應用，顫抖字，第二次看到

**Comment by Rplus** [comment]
Progress Bar Liquid Bubble
http://codepen.io/wiseguy12851/details/mJZNqN/

利用 `border-radius: 40%` 巧妙地製作出波動效果
非常有趣
![image](https://cloud.githubusercontent.com/assets/1808835/9457846/d2696400-4b19-11e5-86c0-ef7569f7cc1c.png)

**Comment by Rplus** [comment]
Amazingly sarcastic click&blink™ bunny! NOW WITH SOUND!!!
http://codepen.io/FabioG/pen/doBEzY

直接 `new Audio` 物件就能播放了耶~
手機也會播
不過 audio format 要挑一下就是了

> http://caniuse.com/#feat=mp3 
> `mp3` 支援最廣

**Comment by Rplus** [comment]
Timer demo
By Bali Balo
http://codepen.io/bali_balo/details/527676fb10a5638253c6897ff73e189b/

很有趣的寫法
用 animation steps time function 來處理時間的遞進

不過不曉得為啥不能 fork ？

---

★續

fork 改成 jade + scss syntax
順便加上 reset 的功能
http://codepen.io/Rplus/pen/jbwLJd/

**Comment by Rplus** [comment]
Flat CSS Eyeball Outline
http://codepen.io/hexagoncircle/pen/RrPgYQ

很有趣~
用 `border-radius` 切成眼睛樣子
很有創意~
![image](https://user-images.githubusercontent.com/1808835/36882432-d279fb06-1e0e-11e8-8bbb-8459033c75f0.png)

**Comment by Rplus** [comment]
http://codepen.io/CrocoDillon/pen/AdtLI
處理地蠻漂亮的 `text-shadow`

巧妙的半透明文字搭配 text-shadow 組成立體陰影
中間的黑色看似無用，但其實是和半透文字色一起稱起第一個灰色的文字陰影~

``` css
.shadow {
  color: rgba(red, .5);
  text-shadow: 0 0.02em 0.08em #ccc, 0 0 0 #000, 0 0.02em 0.02em #fff;
}
```

![image](https://cloud.githubusercontent.com/assets/1808835/12570385/19ff23ba-c412-11e5-99b3-4678e6fe51c3.png)

**Comment by Rplus** [comment]
http://codepen.io/CrocoDillon/pen/Htycs/

`box-shadow` 高級技巧
pseudo-element 的寬度變化 搭配 `box-shadow` 的 dx 位移
順利地用單一偽元素作出反向的兩色塊！
搭起來就是個 slack icon animation 了~

``` scss
  0% {
    width: $thickness;
    box-shadow:
      $lat (-$offset) nth($colors, 1),
      (-$lat) $offset nth($colors, 3);
  }
  35% {
    width: $size;
    box-shadow:
      0 (-$offset) nth($colors, 1),
      0   $offset  nth($colors, 3);
  }
```

![image](https://cloud.githubusercontent.com/assets/1808835/12570503/16efd34e-c413-11e5-858e-e569f743599b.png)
